services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ssmif-dev-challenge
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data